// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package types

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufProviderState = []byte{129}

func (t *ProviderState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufProviderState); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.MetaStateMap (map[string]*types.MetaState) (map)
	{
		if len(t.MetaStateMap) > 4096 {
			return xerrors.Errorf("cannot marshal t.MetaStateMap map too large")
		}

		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajMap, uint64(len(t.MetaStateMap))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.MetaStateMap))
		for k := range t.MetaStateMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.MetaStateMap[k]

			if len(k) > cbg.MaxLength {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := io.WriteString(w, string(k)); err != nil {
				return err
			}

			if err := v.MarshalCBOR(w); err != nil {
				return err
			}

		}
	}
	return nil
}

func (t *ProviderState) UnmarshalCBOR(r io.Reader) error {
	*t = ProviderState{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.MetaStateMap (map[string]*types.MetaState) (map)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajMap {
		return fmt.Errorf("expected a map (major type 5)")
	}
	if extra > 4096 {
		return fmt.Errorf("t.MetaStateMap: map too large")
	}

	t.MetaStateMap = make(map[string]*MetaState, extra)

	for i, l := 0, int(extra); i < l; i++ {

		var k string

		{
			sval, err := cbg.ReadStringBuf(br, scratch)
			if err != nil {
				return err
			}

			k = string(sval)
		}

		var v *MetaState

		{

			b, err := br.ReadByte()
			if err != nil {
				return err
			}
			if b != cbg.CborNull[0] {
				if err := br.UnreadByte(); err != nil {
					return err
				}
				v = new(MetaState)
				if err := v.UnmarshalCBOR(br); err != nil {
					return xerrors.Errorf("unmarshaling v pointer: %w", err)
				}
			}

		}

		t.MetaStateMap[k] = v

	}
	return nil
}
